# frozen_string_literal: true

VAGRANTFILE_API_VERSION = '2'

guest_ip = '192.168.68.101'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'bento/ubuntu-18.04'

  config.vm.define 'bamboo-server' do |host|
    host.vm.hostname = 'bamboo-server.local'
    host.vm.provision 'shell', path: 'provision.sh'
    host.vm.network 'private_network', ip: "#{guest_ip}"
    host.vm.network 'forwarded_port', guest: '8153', host: '8153'

    host.vm.provider 'virtualbox' do |v|
      v.memory = '1024'
      v.cpus = '1'
      v.name = 'Bamboo Server'
    end
  end
end

puts '-------------------------------------------------'
puts " Project URL : http://#{guest_ip}"
puts '-------------------------------------------------'
