---
version: '3.7'
networks:
    teamcity:
        driver: bridge
volumes:
    teamcity-data:
        external: true
    teamcity-logs:
        external: true
    teamcity-agent:
        external: true
services:
    server:
        container_name: teamcity-server
        image: jetbrains/teamcity-server
        volumes:
            - teamcity-data:/data/teamcity_server/datadir
            - teamcity-logs:/opt/teamcity/logs
        networks:
            - teamcity
        ports:
            - 8111:8111
    agent:
        container_name: teamcity-agent
        image: jetbrains/teamcity-agent
        volumes:
            - teamcity-agent:/data/teamcity_agent/conf
        networks:
            - teamcity
        environment:
            - SERVER_URL=http://teamcity-server:8111
