---
version: '3.3'
networks:
    jenkins:
        driver: bridge
volumes:
    jenkins-data:
services:
    server:
        container_name: jenkins-server
        image: jenkins/jenkins:lts
        volumes:
            - jenkins-data:/var/jenkins_home
        networks:
            - jenkins
        ports:
            - 8484:8080
