Description: A target server for CI/CD tests.
Mappings:
  RegionMap:
    ap-northeast-1:
      ami: ami-0f2c38ac2e37197be
    ap-northeast-2:
      ami: ami-0dc961dd0c2c83bdd
    ap-south-1:
      ami: ami-0dba8796fe499ae48
    ap-southeast-1:
      ami: ami-08540b8d2f7fa85a5
    ap-southeast-2:
      ami: ami-0bbcf853aaf6ca4a6
    ca-central-1:
      ami: ami-0de195e1958cc0d52
    eu-central-1:
      ami: ami-0332a5c40cf835528
    eu-north-1:
      ami: ami-34c14f4a
    eu-west-1:
      ami: ami-001b0e20a92d8db1e
    eu-west-2:
      ami: ami-0573b1dbbd809d6c3
    eu-west-3:
      ami: ami-07b2287c6776361c8
    sa-east-1:
      ami: ami-04ab6be036f8635bd
    us-east-1:
      ami: ami-0edd3706ab2e952c4
    us-east-2:
      ami: ami-050553a7784d00d21
    us-west-1:
      ami: ami-065ebd3e6b63c75d5
    us-west-2:
      ami: ami-00f13b45242aff065
Outputs:
  InstanceDnsName:
    Description: PublicDnsName
    Value: !GetAtt 'Instance.PublicDnsName'
Parameters:
  KeyName:
    ConstraintDescription: An existing EC2 KeyPair.
    Description: An existing EC2 KeyPair.
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  EC2SecurityGroup:
    Properties:
      GroupDescription: EC2 Security Group
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          Description: SSH
          FromPort: '22'
          IpProtocol: tcp
          ToPort: '22'
        - CidrIp: '0.0.0.0/0'
          Description: HTTP
          FromPort: '80'
          IpProtocol: tcp
          ToPort: '80'
        - CidrIp: '0.0.0.0/0'
          Description: HTTPS
          FromPort: '443'
          IpProtocol: tcp
          ToPort: '443'
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'
    Type: AWS::EC2::SecurityGroup
  Instance:
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            /tmp/instance.txt:
              content: !Ref 'AWS::StackName'
              group: root
              mode: '000644'
              owner: root
    Properties:
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - ami
      InstanceType: t2.micro
      KeyName: !Ref 'KeyName'
      SecurityGroups:
        - !Ref 'EC2SecurityGroup'
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'
      UserData: !Base64
        Fn::Join:
          - ''
          - - "#!/bin/bash -x\n"
            - "exec > /tmp/user-data.log 2>&1\n"
            - "unset UCF_FORCE_CONFFOLD\n"
            - "export UCF_FORCE_CONFFNEW=YES\n"
            - "ucf --purge /boot/grub/menu.lst\n"
            - "export DEBIAN_FRONTEND=noninteractive\n"
            - "apt-get update\n"
            - "apt-get -o Dpkg::Options::=\"--force-confnew\" --force-yes -fuy upgrade\n"
            - "apt-get install -y nginx supervisor build-essential libssl-dev libffi-dev\
              \ python-pip python3-pip python3-dev python3-setuptools python3-venv\n"
            - "pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz\n"
            - "# Signal Cloudformation when set up is complete\n"
            - /usr/local/bin/cfn-signal -e $? --resource=Instance --region=
            - !Ref 'AWS::Region'
            - ' --stack='
            - !Ref 'AWS::StackName'
            - "\n"
    Type: AWS::EC2::Instance

